package views;

import javax.swing.*;
import javax.swing.event.*;
import java.awt.event.*;

public class TheFrame extends javax.swing.JFrame {

    public void addMovieOrderActionListener(ActionListener listener) {
        movieOrder.addActionListener(listener);
    }

    public String getMovieOrderSelectedItem() {
        return (String) movieOrder.getSelectedItem();
    }

    public void addAddActorActionListener(ActionListener listener) {
        addActor.addActionListener(listener);
    }

    public void addRemoveActorActionListener(ActionListener listener) {
        removeActor.addActionListener(listener);
    }

    public void addAddMovieActionListener(ActionListener listener) {
        addMovie.addActionListener(listener);
    }

    public void addRemoveMovieActionListener(ActionListener listener) {
        removeMovie.addActionListener(listener);
    }

    public void addEditMovieDescriptionActionListener(ActionListener listener) {
        editDescription.addActionListener(listener);
    }

    public void addJoinActionListener(ActionListener listener) {
        joinSelection.addActionListener(listener);
    }

    public void addUnJoinActionListener(ActionListener listener) {
        unjoinSelection.addActionListener(listener);
    }

    public void addClearSelectionActionListener(ActionListener listener) {
        clearSelection.addActionListener(listener);
    }

    public void clearAllSelection() {
        actors.clearSelection();
        movies.clearSelection();
        movieInfo.setText("");
        actorInfo.setText("");
    }

    public void addMoviesListSelectionListener(ListSelectionListener listener) {
        movies.addListSelectionListener(listener);
    }

    public models.Movie getSelectedMovie() {
        return (models.Movie) movies.getSelectedValue();
    }

    public void setMovieText(String text) {
        movieInfo.setText(text);
        movieInfo.setCaretPosition(0); // scroll back to top
    }

    public void addActorsListSelectionListener(ListSelectionListener listener) {
        actors.addListSelectionListener(listener);
    }

    public models.Actor getSelectedActor() {
        return (models.Actor) actors.getSelectedValue();
    }

    public void setActorText(String text) {
        actorInfo.setText(text);
        actorInfo.setCaretPosition(0); // scroll back to top
    }

    public void setMovieRenderer(ListCellRenderer r) {
        movies.setCellRenderer(r);
    }

    public void setActorRenderer(ListCellRenderer r) {
        actors.setCellRenderer(r);
    }

    public void setMoviesModel(ListModel model) {
        movies.setModel(model);
    }

    public void setActorsModel(ListModel model) {
        actors.setModel(model);
    }

    public TheFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        actors = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        movies = new javax.swing.JList();
        movieOrder = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        joinSelection = new javax.swing.JButton();
        unjoinSelection = new javax.swing.JButton();
        clearSelection = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        actorInfo = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        movieInfo = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addActor = new javax.swing.JMenuItem();
        removeActor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addMovie = new javax.swing.JMenuItem();
        removeMovie = new javax.swing.JMenuItem();
        editDescription = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Actors");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Movies");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel2, gridBagConstraints);

        actors.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        actors.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(actors);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        movies.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        movies.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(movies);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jScrollPane2, gridBagConstraints);

        movieOrder.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Title", "Year" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(movieOrder, gridBagConstraints);

        jLabel5.setText("Actor Information:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setText("Movie Information:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabel6, gridBagConstraints);

        joinSelection.setText("Join Selection");
        jPanel2.add(joinSelection);

        unjoinSelection.setText("Un-Join Selection");
        jPanel2.add(unjoinSelection);

        clearSelection.setText("Clear Selection");
        jPanel2.add(clearSelection);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jPanel1, gridBagConstraints);

        actorInfo.setEditable(false);
        actorInfo.setColumns(20);
        actorInfo.setLineWrap(true);
        actorInfo.setRows(5);
        actorInfo.setWrapStyleWord(true);
        jScrollPane3.setViewportView(actorInfo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jScrollPane3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jPanel3, gridBagConstraints);

        movieInfo.setEditable(false);
        movieInfo.setColumns(20);
        movieInfo.setLineWrap(true);
        movieInfo.setRows(8);
        movieInfo.setToolTipText("");
        movieInfo.setWrapStyleWord(true);
        jScrollPane4.setViewportView(movieInfo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jScrollPane4, gridBagConstraints);

        jMenu1.setText("Actor");

        addActor.setText("Add Actor");
        addActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActorActionPerformed(evt);
            }
        });
        jMenu1.add(addActor);

        removeActor.setText("Remove Actor");
        jMenu1.add(removeActor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movie");

        addMovie.setText("Add Movie");
        jMenu2.add(addMovie);

        removeMovie.setText("Remove Movie");
        removeMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMovieActionPerformed(evt);
            }
        });
        jMenu2.add(removeMovie);

        editDescription.setText("Edit Description");
        jMenu2.add(editDescription);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActorActionPerformed

    private void removeMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeMovieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea actorInfo;
    private javax.swing.JList actors;
    private javax.swing.JMenuItem addActor;
    private javax.swing.JMenuItem addMovie;
    private javax.swing.JButton clearSelection;
    private javax.swing.JMenuItem editDescription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton joinSelection;
    private javax.swing.JTextArea movieInfo;
    private javax.swing.JComboBox movieOrder;
    private javax.swing.JList movies;
    private javax.swing.JMenuItem removeActor;
    private javax.swing.JMenuItem removeMovie;
    private javax.swing.JButton unjoinSelection;
    // End of variables declaration//GEN-END:variables
}
